---
# tasks file for create_syntropy_network
- include_vars: ../../../secrets.yaml
- name: Create Syntropy Network
  syntropynet.syntropy.syntropy_network:
     api_url: "{{api_url}}"
     api_token: "{{api_token}}"
     name: "{{network_name}}"
     state: present
     topology: p2m
     connections:
       VM2:
         connect_to:
           Nginx:
             state: present
             services:
               - grafana
             type: tag
           Node-Exporter:
             state: present
             services:
               - node-exporter
             type: tag

         services:
          - prometheus
         type: endpoint
