- include_vars: ../../../secrets.yaml

# Start syntropy agent
- name: Start syntropy agent
  become: true
  docker_container:
      image: syntropynet/agent:stable
      name: syntropynet-agent
      capabilities:
          - NET_ADMIN
          - SYS_MODULE
      env:
          SYNTROPY_API_KEY: "{{api_key}}"
          SYNTROPY_AGENT_NAME: "{{agent_name}}"
          SYNTROPY_PROVIDER: "{{agent_provider}}"
          SYNTROPY_TAGS: "{{agent_tags}}"
          SYNTROPY_NETWORK_API: "docker"

      restart_policy: always
      network_mode: host
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
      devices:
          - /dev/net/tun:/dev/net/tun
