- name: pull an image
  docker_image:
    name: syntropynet/agent:stable
    force_source: yes
- name: Stop and remove old container
  docker_container:
    name: syntropy-agent
    state: absent
    image: syntropy-agent

- name: Deploy Syntropy Agent
  docker_container:
   name: syntropy-agent
   restart_policy: unless-stopped
   image: syntropynet/agent:stable
   network_mode: "{{ NETWORK }}"
   purge_networks: no
   state: started
   env: 
     SYNTROPY_API_KEY: "{{ SYNTROPY_API_KEY }}"
     SYNTROPY_PROVIDER: "{{ SYNTROPY_PROVIDER }}"
     SYNTROPY_NETWORK_API: "{{ SYNTROPY_NETWORK_API }}"
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
   devices:
     - "/dev/net/tun:/dev/net/tun"
   capabilities:
     - net_admin
     - sys_module
